### ISSUE TITLE
服务端怎么实现的？

### ISSUE THREAD

**Issue by SuperChrisliu** [Minf97/videoUdp_miniProgram#1]
1.服务端有开源吗？
2.录音最长10分钟，之后重新开？
3.对比过live-pusher的延迟吗？
4.回音有做处理吗？

**Comment by Minf97** [comment]
1.服务端不开源
2.是的
3.没有对比过。live-pusher要求格式flv等视频格式，与我不符合 ，因此没做
4.暂未处理，在接下来时间考虑使用WebAudioContext过滤回音`https://developers.weixin.qq.com/miniprogram/dev/api/media/audio/WebAudioContext.html`
